# Site
repository: habibfarhan/Resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Habib Ullah Farhan
title: Computer Science Senior
email: habibfarhan512@gmail.com
website: www.github.com/habibfarhan/Resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  habibfarhan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_link: www.linkedin.com/in/habib-ullah-farhan-0691971ab
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: MindBloom
  icon: fas fa-globe
  url: https://studyapp-seven.vercel.app/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Computer Science senior at LUMS with hands-on experience in full-stack development <mark>(MERN)</mark> and a strong interest in building user-centric products. Co-founder of a <mark>D2C startup</mark> and experienced in combining technology with design to improve user experience. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MindBloom
        link: https://studyapp-seven.vercel.app/
        # link_text: Project Website
        additional_links:
          - title:  MindBloom
            icon: fab fa-github
            url: https://github.com/hammdone/studyapp
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An AI driven tool to help users improve focus and combine all their tools.
        description: | # this will include new lines to allow paragraphs
          Built and scaled a direct-to-consumer perfume selling brand, managing marketing, sales, and operations \n Led customer acquisition through digital channels and in person sales \n Oversaw end-to-end business operations, including branding, logistics, and growth strategy
      - layout: top-middle
        title: FindMyStuff
        link: https://github.com/AliAbdullah-1921/SE---43
        description: |
          Built a web application to help students locate lost items within LUMS \n Designed intuitive UX flows and implemented core functionalities for real-world usability \n Improved accessibility and ease of reporting/retrieving lost items

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cadnz
        link: https://cadnz.com/
        # link_text: boringcompany.com
        sub_title: Intern
        caption: June 2025 - August 2025
        quote: >
          Lending automation platform for banks & credit unions
        description: | # this will include new lines to allow paragraphs
          Conducted testing for a fintech application, identifying bugs, usability issues, and design inconsistencies \n Collaborated with developers to improve product performance and user experience \n Contributed to improving software reliability through structured testing and feedback

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lahore University of Management Sciences
        caption: 2022 - 2026
        sub_title: BSc Computer Science

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Learning
      - Boxing
      - Gaming
      - Music

# Footer
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
